<a href="https://colab.research.google.com/github/jollypyun/pytorch/blob/main/PyTorch_%EC%97%B0%EC%82%B0(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from __future__ import print_function
import torch

### 덧셈

In [5]:
x = torch.rand(5,3)
y = torch.rand(5,3)

print(x+y)            # 일반 연산
print(torch.add(x,y)) # torch.add 사용
print(y.add_(x))      # 바꿔치기 방식(꼭 'add' 뒤에 _ 붙일 것)

tensor([[1.2067, 0.8371, 0.6868],
        [0.6937, 0.8427, 0.4040],
        [0.4509, 0.7832, 1.4680],
        [1.0894, 0.5431, 0.1222],
        [1.0754, 0.9650, 1.3110]])
tensor([[1.2067, 0.8371, 0.6868],
        [0.6937, 0.8427, 0.4040],
        [0.4509, 0.7832, 1.4680],
        [1.0894, 0.5431, 0.1222],
        [1.0754, 0.9650, 1.3110]])
tensor([[1.2067, 0.8371, 0.6868],
        [0.6937, 0.8427, 0.4040],
        [0.4509, 0.7832, 1.4680],
        [1.0894, 0.5431, 0.1222],
        [1.0754, 0.9650, 1.3110]])


In [6]:
# 결과 tensor를 인자로 제공
result = torch.empty(5,3)
torch.add(x,y,out = result)
print(result)

tensor([[1.8081, 1.4281, 1.1643],
        [1.2275, 1.3381, 0.7216],
        [0.7531, 1.1646, 2.0022],
        [1.6482, 0.8366, 0.2209],
        [2.0674, 1.7280, 1.7307]])


### 일반

In [7]:
print(x[:,1]) # numpy스러운 인덱싱 표기 가능

tensor([0.5910, 0.4954, 0.3815, 0.2935, 0.7630])


torch.view : tensor의 크기나 모양을 변경.

In [9]:
x = torch.randn(4,4)  # 임의의 4x4 행렬
y = x.view(16)        # 1x16 행렬로 변경
z = x.view(-1,8)      # -1은 다른 차원에서 유추한다는 뜻
print(x,y,z,sep='\n')

tensor([[-0.9787,  0.7277, -0.6306, -0.1897],
        [ 0.8597,  0.6265, -0.3357, -0.4142],
        [ 0.7615, -1.3181, -1.6634,  0.9211],
        [ 1.5216, -0.0481,  1.1547,  1.3253]])
tensor([-0.9787,  0.7277, -0.6306, -0.1897,  0.8597,  0.6265, -0.3357, -0.4142,
         0.7615, -1.3181, -1.6634,  0.9211,  1.5216, -0.0481,  1.1547,  1.3253])
tensor([[-0.9787,  0.7277, -0.6306, -0.1897,  0.8597,  0.6265, -0.3357, -0.4142],
        [ 0.7615, -1.3181, -1.6634,  0.9211,  1.5216, -0.0481,  1.1547,  1.3253]])


.item() : tensor의 값이 하나만 존재한다면, 이것을 사용해 숫자 값을 얻어낼 수 있다.

In [10]:
x = torch.randn(1)
y = x.item()
print(x,y,sep='\n')

tensor([0.4881])
0.48809733986854553
