<a href="https://colab.research.google.com/github/jollypyun/pytorch/blob/main/PyTorch_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from __future__ import print_function
import torch

x = torch.empty(5,3) # 5x3 행렬
print(x)

tensor([[-1.7657e+31,  3.0969e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0969e-41],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22, -5.0609e+30]])


위와 같이 값이 나온 이유은 초기화되지 않은 행렬을 선언하였기 때문이다. 생성이 되면 그 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타난다.

In [4]:
y = torch.rand(5,3)
print(y)

tensor([[0.9641, 0.8211, 0.4505],
        [0.5362, 0.2635, 0.2987],
        [0.0329, 0.5107, 0.6523],
        [0.0283, 0.2960, 0.6242],
        [0.3057, 0.6017, 0.2690]])


rand는 무작위로 초기화된 행렬을 생성합니다.

In [5]:
z = torch.zeros(5,3, dtype = torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


dtype이 long이고 5x3의 영행렬을 생성합니다.

In [6]:
a = torch.tensor([5.5,3])
print(a)

tensor([5.5000, 3.0000])


Tensor는 Numpy의 ndarray와 유사하며, GPU를 사용한 연산 가속도 가능하다.

In [7]:
x = x.new_ones(5,3,dtype = torch.double)
print(x)
x = torch.rand_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.6574, 0.7716, 0.7529],
        [0.4286, 0.1093, 0.7510],
        [0.6525, 0.4324, 0.8856],
        [0.0683, 0.2381, 0.7585],
        [0.0393, 0.0186, 0.1186]])


기존 tensor를 바탕으로 새로운 tensor를 만들 수 있다. 이들 method는 사용자로부터 새로운 값을 제공받지 않는 한, 입력 tensor의 속성들을 재사용한다. (예. dtype)

In [8]:
print(x.size())

torch.Size([5, 3])


행렬의 크기를 구한다. tuple타입이다.